export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const LOAD_DONATIONS_SUCCESS = 'LOAD_DONATIONS_SUCCESS';
export const CREATE_DONATION_SUCCESS = 'CREATE_DONATION_SUCCESS';
export const UPDATE_DONATION_SUCCESS = 'UPDATE_DONATION_SUCCESS';
export const DELETE_DONATION_SUCCESS = 'DELETE_DONATION_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_OK = 'LOGOUT_OK';

